### ISSUE TITLE
Some SVG problems

### ISSUE THREAD

**Issue by vrurg** [css-raku/CSS-Module-raku#11]
I'm currently getting a warning:

```
usage stroke-width: <length-percentage> | inherit | initial
```

But it can also be just `<length>`, see https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-width, for example.

**Comment by vrurg** [comment]
Another one I just've spotted.

```
unknown SVG property: stroke-miterlimit
```

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-miterlimit

**Comment by dwarring** [comment]
Please try again with CSS::Module 0.6.4 which fixes `stroke-width`. `stroke-miterlimit` was added recently and should also now work.

**Comment by vrurg** [comment]
The test suite is now as pure as an angel! :) Thank you!
